import * as Bolumler from './bolumler';
import * as DersDtos from './ders-dtos';
import * as Dersler from './dersler';
import * as OgrenciDtos from './ogrenci-dtos';
import * as SinavDtos from './sinav-dtos';
import * as Sinavlar from './sinavlar';
import * as SinifDtos from './sinif-dtos';
import * as Siniflar from './siniflar';
import * as Volo from './volo';
import * as YetkiliDtos from './yetkili-dtos';
export { Bolumler, DersDtos, Dersler, OgrenciDtos, SinavDtos, Sinavlar, SinifDtos, Siniflar, Volo, YetkiliDtos };
